### ISSUE TITLE
Few Suggestions and thoughts

### ISSUE THREAD

**Issue by SlowLogicBoy** [JackRyder/Otaku-Time#1]
I looked through your code and fiddled with it and I have few suggestions:

- [ ] Move Phantom Stuff to it's own class instead of using Static everywhere:
Make interface like `IAnimeProvider`.
Then using that you could make `KissAnimeProvider`, `KissCartoonProvider`, `KissLewdProvider`.
If you have some common methods you want to reuse make abstract class `KissProvider`.
`IAnimeProvider` methods:
`Task<List<Anime>> GetTopAnimeAsync(); `
`Task<List<AnimeEpisode>> GetAnimeEpisodesAsync(Anime anime); `
`Task<List<AnimeEpisode>> SeachAnimeAsync(string keywords); `
`Task<string> GetEpisodeUrlAsync(AnimeEpisode);`
this doesn't have to be exactly the same since Anime is provided only by KissAnime, maybe `Series` model and `SeriesEpisode`.
Also this way you will be able to create more providers later for other sites :).
- [ ] Since you need same provider(PhantomJS) almost everywhere you could 
    * construct it only in MainWindow and pass it everywhere
    * assign to properties
    * `MEF` - this is what I use, I Import Lazy Property
- [x] You also have recursions happening, which I fixed, try to avoid them :) (maybe I will file a PR, but I did too much, so I need to clean that up before that).

- [x] By the way I haven't seen a license anywhere, I hope it's ether MIT or BSD ^^.

Thanks to your work I started my own project a bit differently (maybe we will be able to merge them someday):
* I use [Eto.Forms](https://github.com/picoe/Eto) its similar to WinForms but works on linux and mac
* As mentioned previously I use `MEF` to pass around stuff
* To save some data/settings I use [LiteDB](https://github.com/mbdavid/LiteDB)
* Since I use MyAnimeList I based my project on it (for those who don't use MAL I would make localdb where I could save progress):
    * Download and display MAL List
    * With that I can look up anime episodes using your work (that I'm currently watching)
[Here is quick and dirty mockup](https://www.dropbox.com/s/so37btn5q53fzkj/2017-08-06%2020-13-07.mp4?dl=0)
    * Future:
        * Background check for new epsiodes
        * Automatically update MAL on eps you have watched.
        * Get sequels prequels and recommendations

**Comment by JackRyder** [comment]
Hey,

I have plans in the future to integrate it a lot better with MAL, and making it a lot more adaptive. I do want to redesign it completely but it'll take time and stuff will break, which then means fixing stuff.

PhantomJS was originally in it's own class using the singleton methodology in order to make sure i dont have to reauth all the time, but I was just trying to limit the amount of classes I had to create, and since the PhantomObject is technically static, I feel like it works.

I'll keep this issue open and run through some of the suggestions when I get time :)

Thanks!

**Comment by JackRyder** [comment]
Also, which recursions do you mean that you fixed? Most of the recursion I used were retries in case of failures. Recusion isn't always bad, only bad if not handled correctly and are prone to deadlocking :)

**Comment by SlowLogicBoy** [comment]
I solved some of recursions, I just can't file PR yet :)

**Comment by JackRyder** [comment]
Hey, i've added the rest of the changes to backlog so i'll work on them sometime when I get chance. Thanks for the suggestions, i'm gunna close this issue :+1:
