### ISSUE TITLE
Proposal. Export Text links feature.

### ISSUE THREAD

**Issue by pachimonopower** [JackRyder/Otaku-Time#3]
Otaku-Time is good software.
but i hope to do use other downloader.
how about this?
thank you

**Comment by JackRyder** [comment]
Which downloaders do you have in mind?

**Comment by pachimonopower** [comment]
it is jdownloader2.

**Comment by JackRyder** [comment]
Ah right okay, sad to hear you don't want to use my downloader functionality, but i'll see what I can do for next release :)

**Comment by pachimonopower** [comment]
I'm sorry...thank you for thinking 😃

**Comment by JackRyder** [comment]
I saw you did your own version of this, but I've just finished and pushed my version to master! 

Issue completed!
