### ISSUE TITLE
Not found anime. But it exists on the site.

### ISSUE THREAD

**Issue by pachimonopower** [JackRyder/Otaku-Time#4]
Hi.

i was searching the anime, and found target title anime but otaku-time is can not found animation.
that is like url is below↓
http://*************.**/M/Anime/Suite-Precure♪
(it might be last char garbled)

Source code from SingleLoadedAnime class.
_phantomObject.Navigate().GoToUrl(AnimeUrl);
It looks like selenium webdriver is don't move to anime url.
I am investigating the cause.

thank you.

**Comment by JackRyder** [comment]
Hey,

If you fix it, let me know and submit a PR and i'll get it merged in :+1:  If not let me know and i'll take a look

**Comment by pachimonopower** [comment]
thank you read.
i was complete the fix just now. to #6
regards.

**Comment by JackRyder** [comment]
Closing due to you fixing it, thanks for the PR :1st_place_medal:
